### ISSUE TITLE
Console warning for source langage translations

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/nextcloud-l10n#108]
As we use `en` as source language and provide no translations for it, `node-gettext` shows a warning every time a translation is requested. I think this could be fixed with https://github.com/alexanderwallin/node-gettext/pull/36.

**Comment by ChristophWurst** [comment]
cc @nickvergessen because you noticed as well

**Comment by nickvergessen** [comment]
yeah, but the PR is from 2017, so doesnt look like its ever being merged?

**Comment by ChristophWurst** [comment]
That is why I asked the repo owner https://github.com/alexanderwallin/node-gettext/pull/36#issuecomment-606661389. Let's see.

**Comment by ChristophWurst** [comment]
> yeah, but the PR is from 2017

SEE https://github.com/alexanderwallin/node-gettext/pull/36#issuecomment-606696030 :grinning:

**Comment by nickvergessen** [comment]
So, update to 2.1 and lets get this in?

**Comment by ChristophWurst** [comment]
v1.2 released :rocket:

**Comment by nickvergessen** [comment]
And now we update the nextcloud-vue lib and then all apps, right?

**Comment by ChristophWurst** [comment]
Yes

**Comment by ChristophWurst** [comment]
nc-vue and nc-moment updates triggered on Dependabot

**Comment by ChristophWurst** [comment]
But I'd say this is not urgent, right?

**Comment by nickvergessen** [comment]
> But I'd say this is not urgent, right?

Yeah, just wondered what actually is causing the spam in the end, but I guess it's mostly the -vue library

**Comment by raimund-schluessler** [comment]
Can one somehow also disable these warnings in jest tests? I still see this for many tests in Tasks (e.g. https://github.com/nextcloud/tasks/runs/644815302#step:6:14), and would like to get rid of it, but don't know how. `OC` is actually globally defined (https://github.com/nextcloud/tasks/blob/master/tests/javascript/unit/setup.js#L10), but for some reason `nextcloud/l10n` doesn't find it, and warns about it.

**Comment by ChristophWurst** [comment]
> but for some reason `nextcloud/l10n` doesn't find it, and warns about it

This is strange. Are you sure `global` is the object used as global namespace during test execution? Could you add a console.log(OC) to your tests and see if that find your stub?

**Comment by raimund-schluessler** [comment]
> This is strange. Are you sure `global` is the object used as global namespace during test execution? Could you add a console.log(OC) to your tests and see if that find your stub?

Yes, it correctly logs the OC object, that's why I wonder why its not found by l10n.

**Comment by ChristophWurst** [comment]
Mind linking this package to your app, adding a console log here as well and see if `OC` really is undefined?

**Comment by raimund-schluessler** [comment]
It seems it has something to do with mocking the date

```
import { OC } from './OC.js'
import moment from '@nextcloud/moment'
// eslint-disable-next-line node/no-unpublished-import
import MockDate from 'mockdate'

// Set date to fixed value
MockDate.set(moment('20190101T123456', 'YYYYMMDDTHHmmss'))

global.OC = new OC()
```

When I don't import nextcloud/moment here, these warning disappear (but the tests fail, because the today date is used).

**Comment by raimund-schluessler** [comment]
Not using `nextcloud/moment` in the setup file, but a simple javascript date like
```
MockDate.set(new Date('2019-01-01T12:34:56'))
```
fixes the issue. Seem like `OC` is not defined in the setup file, but only for the tests, I guess. Anyway, the warnings are gone and the tests pass. 👍

**Comment by raimund-schluessler** [comment]
Just for the sake of completeness, here is the PR which fixes the problems for Tasks https://github.com/nextcloud/tasks/pull/1010
