### ISSUE TITLE
Issue in Vue with code injection prevention

### ISSUE THREAD

**Issue by julien-nc** [nextcloud/nextcloud-l10n#243]
When found in a translation variable, some characters (`' " < >` etc...) are replaced with their html char code. Problem is, with Vue, the code is displayed instead of the character.

refs https://github.com/nextcloud/server/issues/26113

In this issue, the user display name ends with a single quote. The dashboard greeting is then
```
<h2>Good morning, NAME&#39;</h2>
```

@skjnldsv @ma12-co @PVince81 Does it ring a bell? How can we deal with such cases?

**Comment by ChristophWurst** [comment]
https://github.com/nextcloud/server/issues/18662

**Comment by susnux** [comment]
So this is fixed?

**Comment by skjnldsv** [comment]
Seems like it, I never had this issue :shrug:
