### ISSUE TITLE
Move OC.L10N.translate to this library

### ISSUE THREAD

**Issue by PVince81** [nextcloud/nextcloud-l10n#271]
Currently, the library relies on an existing global function "translate" that is defined in the server's OC namespace.

We should move it here.

1) Move the server's translate() implementation into this library
2) Release the library
3) Make the server code use the library in its `OC.L10N.translate` implementation

**Comment by PVince81** [comment]
Context: I was trying to mock "translate()" first when writing Jest tests but realized that I needed the full formatting implementation.
Since the server repo JS code is not available within the context of app tests, I wanted to use the full implementation of nextcloud-l10n. But it failed because that one is also relying on server repo JS code.

Once this ticket is solved it will be possible to use `translate()` and `translatePlural()` without mocking.

**Comment by ChristophWurst** [comment]
Sounds good :+1: 

This is also how we moved out most of the other packages. The only thing that will most likely have to remain in server is the code that allows registration of translation strings from the js files that we load.
