### ISSUE TITLE
"No OC found" console warning in 24+

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/nextcloud-l10n#433]
https://github.com/nextcloud/nextcloud-l10n/blob/master/lib/index.ts#L26-L30

**Comment by ChristophWurst** [comment]
The global variable should still be there. Is your app's code run too early, before the server js has been loaded?

**Comment by nickvergessen** [comment]
I don't know which code it is. It showed on the login page and the dashboard in the console for me.

**Comment by ChristophWurst** [comment]
![Bildschirmfoto vom 2022-05-02 13-13-01](https://user-images.githubusercontent.com/1374172/166225228-f8bccf61-4879-438a-86e5-4350e63036b8.png)

It's a few of the core bundles and files_rightclick. @artonge @vanpertsch could you have a look? I think some shipped apps load before the Nextcloud bundles.

**Comment by artonge** [comment]
@ChristophWurst  I can't reproduce the errors, can you point me to where you triggered them? I can reproduce the warning though.

**Comment by nickvergessen** [comment]
You have to be "lucky" I guess as the order is undefined, it might also (depending on the loading speed) be served in the correct order?

**Comment by ChristophWurst** [comment]
Okay now I am confused. I certainly could trigger it opening `/login` in a private window on our internal instance. I can also no longer see it
