### ISSUE TITLE
Wrong TranslationOption

### ISSUE THREAD

**Issue by georgehrke** [nextcloud/nextcloud-l10n#67]
It's called `escape`, not `escaped`

https://github.com/nextcloud/nextcloud-l10n/blob/master/lib/index.ts#L31

https://github.com/nextcloud/server/blob/master/core/src/OC/l10n.js#L86
https://github.com/nextcloud/server/blob/master/core/src/OC/l10n.js#L137

**Comment by ChristophWurst** [comment]
Whoopsie. Strictly speaking that makes a breaking change :see_no_evil:
