### ISSUE TITLE
Provide an isRTL method

### ISSUE THREAD

**Issue by tcitworld** [nextcloud/nextcloud-l10n#84]
> Imho it would be better if nextcloud/l10n provided an isRTL method, so we can simply flip it around.

_Originally posted by @georgehrke in https://github.com/nextcloud/calendar/pull/1933_

**Comment by ChristophWurst** [comment]
Sure. How would it work? Is this derivable from the locale?

**Comment by tcitworld** [comment]
It seems the tools that provide this feature use an hardcoded list:
* https://github.com/i18next/i18next/blob/master/src/i18next.js#L392
* https://github.com/shadiabuhilal/rtl-detect/blob/master/lib/rtl-detect.js#L136

**Comment by ChristophWurst** [comment]
Makes sense. I whish there was a shared list of these locales as npm package. Feels strange that everyone maintains their own :see_no_evil:

**Comment by susnux** [comment]
Maybe this is helpful: https://www.npmjs.com/package/rtl-detect
